{"name": "Успешное получение заказов с авторизацией - возвращается ожидаемый статус 200", "status": "passed", "start": 1748983316422, "stop": 1748983317124, "uuid": "47da0c3e-5cfc-494a-9626-3a9ffa9b881a", "historyId": "24562fab5e48e3138cd01f74ed0091dd", "testCaseId": "24562fab5e48e3138cd01f74ed0091dd", "fullName": "tests.test_get_orders.TestGetOrdersWithAuth#test_get_orders_with_auth_status_200", "labels": [{"name": "feature", "value": "Получение заказов"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders"}, {"name": "subSuite", "value": "TestGetOrdersWithAuth"}, {"name": "host", "value": "MaxPro"}, {"name": "thread", "value": "2704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders"}]}