{"name": "Неуспешное обновление данных пользователя без авторизации - возвращается сообщение о не авторизированном сообщении", "status": "passed", "parameters": [{"name": "data_field", "value": "'email'"}], "start": 1748983315694, "stop": 1748983315899, "uuid": "869928a9-0b06-49ff-8338-269caae3548c", "historyId": "ea6d95e3485f7cfdac5ca76a803c0fe6", "testCaseId": "15fdf09852331402c6d1f52fa6b17097", "fullName": "tests.test_edit_user.TestEditUser#test_update_user_without_auth_message", "labels": [{"name": "feature", "value": "Изменение данных пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_edit_user"}, {"name": "subSuite", "value": "TestEditUser"}, {"name": "host", "value": "MaxPro"}, {"name": "thread", "value": "2704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_edit_user"}]}